name: 'Kiali Epic Action'
description: 'Sync Epic and Subtask Issues with a list of tasks'
inputs:
  TOKEN:
    description: "Github token"
    default: ""
branding:
  icon: 'align-left'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'